# Generated by Django 5.2.12 on 2026-03-25 15:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcenterdata',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='healthcenterdata',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
