# Generated by Django 5.2.12 on 2026-03-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_healthcenterdata_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
