# Generated by Django 5.2.12 on 2026-03-25 23:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_internetdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internetdata',
            name='name',
        ),
        migrations.AddField(
            model_name='internetdata',
            name='brandname',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='internetdata',
            name='environmnt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internetdata',
            name='frn',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='internetdata',
            name='h3_res9_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='internetdata',
            name='mindown',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internetdata',
            name='minsignal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internetdata',
            name='minup',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internetdata',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='internetdata',
            name='providerid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internetdata',
            name='technology',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
